library(shiny)
library(DT)
library(dplyr)
library(readr)
library(here)
library(shinyWidgets)

# === Load cleaned data ===
data_file <- "FQHC_evaluation_data.csv"
comparison_df <- read_csv(data_file, show_col_types = FALSE)

# Making sure 'Measure' column exists
if (!"Measure" %in% names(comparison_df)) {
  comparison_df$Measure <- comparison_df$Disparity
}

# Adding editable FQHC columns
if (!"FQHC Progress (%)" %in% names(comparison_df)) {
  comparison_df$`FQHC Progress (%)` <- 0
}

# === UI ===
ui <- navbarPage(
  title = "\U0001F4CA Haralson Health Collective Disparities KPI Dashboard",
  id = "main_nav",
  
  # === Custom CSS ===
  header = tags$head(
    tags$style(HTML("
      body { background-color: #4D7952; color: white; }
      .selectize-input {
        background-color: #d9d9d9 !important;
        color: black !important;
        border-radius: 4px;
      }
      .selectize-dropdown, .selectize-dropdown-content {
        background-color: #f0f0f0 !important;
        color: black !important;
      }
      table.dataTable thead {
        background-color: #4D7952;
        color: white;
      }
      table.dataTable tbody {
        background-color: #C3D3C6;
        color: black;
      }
      table.dataTable tbody tr:hover {
        background-color: #8BB4C7 !important;
      }
      .dataTables_wrapper .dataTables_paginate .paginate_button {
        color: black !important;
        background: none !important;
        border: none !important;
      }
      .dataTables_wrapper .dataTables_paginate .paginate_button:hover {
        color: #000 !important;
        text-decoration: underline;
      }
      .dataTables_wrapper .dataTables_paginate .paginate_button.current {
        background-color: #03787d !important;
        color: white !important;
        font-weight: bold;
      }
      .shiny-input-container input:focus,
      .shiny-input-container select:focus {
        outline: 2px solid #fcd116;
        box-shadow: 0 0 10px #fcd116;
      }
      .shiny-input-container label[for='disparity_filter'] {
        color: #d3d3d3 !important;
      }
    "))
  ),
  
  # === Dashboard Tab ===
  tabPanel("Dashboard",
           sidebarLayout(
             sidebarPanel(
               selectInput("disparity_filter", "Filter by Disparity:",
                           choices = c("All", unique(comparison_df$Disparity)), selected = "All"),
               helpText("Compare Haralson County's rates with GA, US, and the FQHC's performance.")
             ),
             mainPanel(
               h4("Comparative KPI Table with Progress Bars"),
               DTOutput("comparison_dt"),
               br(),
               uiOutput("progress_bars"),
               br(),
               h4("Key Takeaways"),
               p("This dashboard tracks the progress of our proposed-FQHC toward achieving health equity goals. It is used to assess disparities, adjust internal targets, and guide improvement efforts."),
               br(),
               p(strong("Real World Impact:"),
                 "This tool helps our proposed-FQHC track disparities, guide care coordination, and align with Healthy People 2030.")
             )
           )
  ),
  
  # === Dataset Info Tab ===
  tabPanel("Dataset Info",
           fluidPage(
             h4("Dataset Description"),
             p("The data used in this dashboard is from HealthyPeople2030 and PLACES.PLACES data is collected and generated by using data from the Behavioral Risk Factor Surveillance System, U.S. Census Bureau data (population counts and estimates), and the American Community Survey (ACS). "),
             p("Sample size: population size (30,548."),
             p("The FQHC data will be manually compiled by clinical staff from EHR summaries and performance reports."),
             p("Study population includes underserved patients in Haralson County, GA."),
             p("Time period: January 2023 – March 2025.")
           )
  )
)


# === Server ===
server <- function(input, output, session) {
  # Reactive comparison_df so updates propagate
  reactive_df <- reactiveVal(comparison_df)
  
  # Reactive filtered data
  filtered_data <- reactive({
    df <- reactive_df()
    if (input$disparity_filter == "All") {
      df
    } else {
      df %>% filter(Disparity == input$disparity_filter)
    }
  })
  
  # editable DT table
  output$comparison_dt <- renderDT({
    datatable(
      filtered_data(),
      editable = list(target = 'cell'),
      rownames = FALSE,
      options = list(
        pageLength = 10,
        autoWidth = TRUE,
        dom = 't<"dt-footer"ip>'
      ),
      class = 'stripe hover cell-border row-border compact'
    )
  }, server = FALSE)
  
  # progress bars
  output$progress_bars <- renderUI({
    df <- filtered_data()
    tagList(
      lapply(1:nrow(df), function(i) {
        progress <- df$`FQHC Progress (%)`[i]
        target <- df$`HP2030 Target`[i]
        gap <- target - progress
        color <- ifelse(is.na(progress), "gray",
                        ifelse(gap <= 5, "success",
                               ifelse(gap <= 15, "warning", "danger")))
        
        tagList(
          tags$strong(df$Measure[i]),
          progressBar(
            id = paste0("bar_", i),
            value = progress,
            total = target,
            status = color,
            display_pct = TRUE
          ),
          p(em("Gap to target:"), paste0(round(gap, 1), "%"))
        )
      })
    )
  })
  
  # Update reactive_df on DT cell edit
  observeEvent(input$comparison_dt_cell_edit, {
    info <- input$comparison_dt_cell_edit
    df <- reactive_df()
    filtered_df <- filtered_data()
    
    i <- info$row
    j <- info$col
    colname <- names(filtered_df)[j + 1]  
    val <- as.numeric(info$value)
    
    match_row <- which(df$Measure == filtered_df$Measure[i] & df$Disparity == filtered_df$Disparity[i])
    df[match_row, colname] <- val
    reactive_df(df)  
  })
}

# === Run App ===
shinyApp(ui, server)
